[target.x86_64-unknown-linux-musl]
image = "registry.gitlab.com/rust_musl_docker/image:stable-latest"

[build.env]
passthrough = [
    "KVENV_TENANT_ID",
    "KVENV_CLIENT_ID",
    "KVENV_CLIENT_SECRET",
    "KVENV_KEYVAULT_NAME",
    "KVENV_SECRET_NAME",
]
